### ISSUE TITLE
Android ML Kit Firebase FirebaseVisionText, block.getCornerPoints() always returns null value. 

### ISSUE THREAD

**Issue by androidsparkling** [firebase/snippets-android#102]
![image](https://user-images.githubusercontent.com/22494719/56641035-019f8280-6692-11e9-964c-ca90c22f0475.png)

**Comment by samtstern** [comment]
Duplicate of https://github.com/firebase/quickstart-android/issues/866

@androidsparkling please try not to post duplicate issues!
