### ISSUE TITLE
feature requests leads to nothing

### ISSUE THREAD

**Issue by obitodarky** [firebase/snippets-android#108]
in the [CONTRIBUTING.md](https://github.com/firebase/snippets-android/blob/master/CONTRIBUTING.md) the Feature Requests sub-cat (that should be at: https://github.com/firebase/snippets-android/blob/master/CONTRIBUTING.md#feature)  leads to nothing. Should it be added/removed?
![Screenshot 2019-05-21 at 11 33 27 AM](https://user-images.githubusercontent.com/21317964/58072496-801e1000-7bbd-11e9-9fcf-adaf973da409.png)

**Comment by samtstern** [comment]
Nice catch thanks @obitodarky
