### ISSUE TITLE
An internal error has occurred

### ISSUE THREAD

**Issue by DTIPMAM** [firebase/snippets-android#182]
Requests to this API identitytoolkit method google.cloud.identitytoolkit.v1.AuthenticationService.SignUp are blocked.

**Comment by rosariopfernandes** [comment]
@DTIPMAM I believe you're trying to use Multi-Factor Authentication. As mentioned [here](https://github.com/firebase/quickstart-android/blob/master/auth/README.md#multi-factor-authentication):

> Multi Factor authentication only works for apps using [Google Cloud Identity Platform](https://cloud.google.com/identity-platform/docs/android/mfa), a paid service.

**Comment by samtstern** [comment]
Thanks @rosariopfernandes I think you're right.

@DTIPMAM if you're having issues with the Firebase Android SDK please file them on the official SDK repo (this repo is just snippets) or contact Firebase support.

**Comment by DTIPMAM** [comment]
> Obrigado @rosariopfernandes Acho que você está certo.
> 
> @DTIPMAM, se você estiver tendo problemas com o SDK do Firebase Android, registre-os no repositório oficial do SDK (este repositório são apenas trechos) ou entre em contato com o suporte do Firebase.


I'm using the anonymous authentication method


			  mAuth.signInAnonymously()
				 .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
					 @Override
					 public void onComplete(@NonNull Task<AuthResult> task) {
						 pg.dismiss();
						 if (task.isSuccessful()) {
							 Log.d(TAG, "signInAnonymously:success");
							 Intent it = new Intent(getBaseContext(), CadastroFirebaseActivity.class);
							 start_activity(it);
						 } else {
							 Log.w(TAG, "signInAnonymously:failure", task.getException());
							 Toast.makeText(ctx, "Authentication failed.", Toast.LENGTH_SHORT).show();
						 }

					 }
				 });

**Comment by DTIPMAM** [comment]
> @ DTIPMAM Acredito que você esteja tentando usar a autenticação multifator . É mencionado [aqui](https://github.com/firebase/quickstart-android/blob/master/auth/README.md#multi-factor-authentication) :
> 
> > A autenticação multifator funciona apenas para aplicativos que usam o [Google Cloud Identity Platform](https://cloud.google.com/identity-platform/docs/android/mfa) , um serviço pago.


my App is correctly configured according to the firebase documentation however when i try to login or add a user give the following error
  com.google.firebase.FirebaseException: An internal error has occurred. [Requests to this API identitytoolkit method google.cloud.identitytoolkit.v1.AuthenticationService.SignUp are blocked. ]

**Comment by samtstern** [comment]
It looks like it may be the same as this issue:
https://stackoverflow.com/questions/52970822/firebase-auth-internal-error-signup-are-blocked-on-web
