### ISSUE TITLE
new AUTHUI reeor

### ISSUE THREAD

**Issue by Ppolka** [firebase/snippets-android#239]
https://github.com/firebase/snippets-android/blob/82c214e66547830dd9f8cbe66019e616f22881e6/auth/app/src/main/java/com/google/firebase/quickstart/auth/FirebaseUIActivity.java#L31-L45

**Comment by Ppolka** [comment]
new auth ui error

**Comment by morganchen12** [comment]
Hey Ppolka, looks like you've filed this issue in the wrong repository. Please file a new issue at FirebaseUI-Android via [this link](https://github.com/firebase/FirebaseUI-Android/issues/new). Make sure you fill out the issue template, and include complete steps to reproduce the error you're seeing. If you're unable to do so, make sure you share the error message itself.
