### ISSUE TITLE
procamedurgsus-ASSIAPLI#/auth

### ISSUE THREAD

**Issue by ASSIAPLI** [firebase/snippets-android#268]
https://github.com/firebase/snippets-android/blob/686d8e61edab387ae35c3b6cb2d666b936d54f79/installations/app/src/main/java/com/google/samples/snippet/kotlin/MainActivity.kt#L53com/procamedurgsus-ASSIAPLI#/auth

**Comment by ASSIAPLI** [comment]
Adicionei procamedurgsus-ASSIAPLI#/auth
Será que pedirá o conhecimento de problemas nesse grupo ou nas avaliações desses projetos? Dê suas sugestões.

**Comment by samtstern** [comment]
@ASSIAPLI please file issues in English (it's the only language I speak) and use the issue template.
