### ISSUE TITLE
Depreciated method - please update documentation

### ISSUE THREAD

**Issue by wuujcik** [firebase/snippets-android#280]
https://github.com/firebase/snippets-android/blob/0cb086ce369b149772f265c92498d1b31a3660fe/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIActivity.kt#L29-L36

`startActivityForResult(Intent,int)` is deprecated, please update your snippet and documentation

**Comment by samtstern** [comment]
Thanks for the feedback @wuujcik!  As far as I know the `startActivityForResult()` method is not actually deprecated:
https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)

Although you're correct that it's no longer recommended:
https://developer.android.com/training/basics/intents/result

I think what we need to do here is ship an `ActivityResultContract` in the FirebaseUI library which would enable developers to safely use the shiny new API!

**Comment by rosariopfernandes** [comment]
@samtstern the `startActivityForResult` and `onActivityResult` methods have been deprecated in the [androidx.activity library v1.2.0](https://developer.android.com/jetpack/androidx/releases/activity#version_120_3). I only see deprecation warnings in projects using that library.



@wuujcik Thanks for bringing this up. As @samtstern mentioned, this should be done in the FirebaseUI library and might come out in the next release of that library (see firebase/FirebaseUI-Android#1918 )

**Comment by kolaviswanath** [comment]
> https://github.com/firebase/snippets-android/blob/0cb086ce369b149772f265c92498d1b31a3660fe/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIActivity.kt#L29-L36
> 
> `startActivityForResult(Intent,int)` is deprecated, please update your snippet and documentation

Delete

**Comment by aditmodhvadia** [comment]
Any updates on the deprecation of startActivityForResult()?

**Comment by rosariopfernandes** [comment]
I think this has been solved by #303

**Comment by samtstern** [comment]
@rosariopfernandes thanks!
