### ISSUE TITLE
Replace use of "whitelist" in code snippets with "access list" or "allow list"

### ISSUE THREAD

**Issue by gtknoke** [firebase/snippets-android#320]
Our public style guide forbids use of the term "whitelist" in favor of more neutral terms like "access control list", "access list", or "allow list". Samples from this repo containing those terms are included in pages on firebase.google.com and need to be updated to comply with our updated style guide.

**Comment by thatfiredev** [comment]
@gtknoke I couldn't find any usages of [whitelist](https://github.com/firebase/snippets-android/search?q=whitelist) or [blacklist](https://github.com/firebase/snippets-android/search?q=blacklist) in this repo. Can you point to a specific file?

**Comment by Meechi25** [comment]
AI private lateinit var auth: FirebaseAuth
// ...
// Initialize Firebase Auth
auth = Firebase.auth

**Comment by morganchen12** [comment]
Closing since no action needs to be taken.

**Comment by ChinoJones** [comment]
appcheck/app/src/main/java/com/google/firebase/example/appcheck/kotlin/ApiWithAppCheckExample.kt
