### ISSUE TITLE
Docs: Code snippet for City class does not match Java version

### ISSUE THREAD

**Issue by paulsmithkc** [firebase/snippets-android#322]
#### Environment details

Documentation on https://firebase.google.com/

#### Steps to reproduce

  1. Open the [Add data to Cloud Firestore](https://firebase.google.com/docs/firestore/manage-data/add-data) page in the docs.
  2. Compare the "Java" and "Java Android" code snippets under [Custom objects](https://firebase.google.com/docs/firestore/manage-data/add-data#custom_objects)
  3. Notice that there a significant inconsistencies, and that both versions only show part of the class.

#### External references such as API reference guides

- https://firebase.google.com/docs/firestore/manage-data/add-data#custom_objects
- https://firebase.google.com/docs/firestore/query-data/get-data#custom_objects

#### Any additional information below

Related issue on Java snippet https://github.com/googleapis/java-firestore/issues/876

See pull request https://github.com/firebase/snippets-android/pull/323

**Comment by thatfiredev** [comment]
@paulsmithkc Thanks for bringing this up and putting together a PR.

I don't think they were ever meant to match, since those are 2 different SDKs: "Java Android" uses the Android Client SDK while "Java" uses the Java Admin SDK.
