### ISSUE TITLE
what is need to be done here basically ?

### ISSUE THREAD

**Issue by ShreeOcean** [firebase/snippets-android#342]
https://github.com/firebase/snippets-android/blob/42a07d076b5fa82501f349f5b645a0ca0a8d664f/auth/app/src/main/java/com/google/firebase/quickstart/auth/PhoneAuthActivity.java#L160

**Comment by thatfiredev** [comment]
@ShreeOcean It's up to you, whatever you want to do when the authentication finishes. You can update a `TextView` or take the user to a new screen, etc.

We have a sample app in [firebase/quickstart-android](https://github.com/firebase/quickstart-android/tree/master/auth) where the `updateUI` method displays a "Authentication Successful" text on a `TextView`:

https://github.com/firebase/quickstart-android/blob/77cbc3ecaf38c4496e1c62a06320d2f00d0ef4db/auth/app/src/main/java/com/google/firebase/quickstart/auth/java/PhoneAuthFragment.java#L293-L308
