### ISSUE TITLE
Align documentation and code sample on how to manually track screens

### ISSUE THREAD

**Issue by flyrev** [firebase/snippets-android#356]
The Google Analytics documentation, under [Manually track screens](https://firebase.google.com/docs/analytics/screenviews#manually_track_screens), says:

> You can manually log screen_view events whether or not automatic tracking is enabled. You can log these events in the onAppear or viewDidAppear methods for Apple platforms and **onResume for Android**. When screen_class is not set, Analytics sets a default value based on the UIViewController or Activity that is in focus when the call is made.

The [code sample](https://github.com/firebase/snippets-android/blob/7127256e50fffc2a34db02986dc629443b6f56d1/analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt#L245-L248), however, does it [inside onCreate](https://github.com/firebase/snippets-android/blob/7127256e50fffc2a34db02986dc629443b6f56d1/analytics/app/src/main/java/com/google/firebase/example/analytics/kotlin/MainActivity.kt#L42).

Looking at the [lifecycle](https://developer.android.com/reference/android/app/Activity.html#activity-lifecycle), having it in `onResume` would mean that after the device wakes from sleep, another event would be sent.

**Comment by thatfiredev** [comment]
@flyrev the `screen_view` event should be logged from `onResume`. This repo (snippets-android) is only used as a backing source for our docs, so most of the times we don't really take in consideration where each method is being called from. Our [quickstart samples](https://github.com/firebase/quickstart-android) are the ones that we tell developers to use as "code samples", and it already calls it in `onResume`:

https://github.com/firebase/quickstart-android/blob/6945fb0a9d20b5dc3597209493e30792022b08f7/analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt#L99

For consistency, however, I would be happy to change the call in this repo from `onCreate` to `onResume`. Let me know if you'd like to send us a PR :)

**Comment by AlbertoYabeda** [comment]
Hello, Can you assign it to me?

**Comment by thatfiredev** [comment]
Done in #408 

Thanks @AlbertoYabeda

**Comment by AlbertoYabeda** [comment]
Always @thatfiredev
