### ISSUE TITLE
Firebase.auth appears as unresolved reference

### ISSUE THREAD

**Issue by clcmo** [firebase/snippets-android#390]
I'll try to use the Firebase auth reference on my project, but it won't works.

https://github.com/firebase/snippets-android/blob/61b336de5aab6145f44fcaecde9f26366e0fff46/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/CustomAuthActivity.kt#L28

**Comment by thatfiredev** [comment]
Hi @clcmo

Make sure you're using the Firebase dependency suffixed with `-ktx`:

```groovy
implementation 'com.google.firebase:firebase-auth-ktx'
```

You can also refer to our documentation on how to [setup Firebase Auth on Android](https://firebase.google.com/docs/auth/android/start#kotlin+ktx).

**Comment by thatfiredev** [comment]
@clcmo It's been a while since this issue has opened, so I'm going to close it now.
Feel free to re-open if you're still facing this issue.

**Comment by ChinoJones** [comment]
import com.google.firebase.auth.ktx.auth
import com.google.firebase.ktx.Firebase

**Comment by ChinoJones** [comment]
Patch
