### ISSUE TITLE
Android: 4086536922265579220

### ISSUE THREAD

**Issue by HMSALNGM** [firebase/snippets-android#443]
https://github.com/firebase/snippets-android:4086536922265579220/blob/d60225ad42a572f30a976459dc4c7a2ac82463f7/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/FirebaseUIActivity.kt#L33-L46

**Comment by thatfiredev** [comment]
@HMSALNGM Are you having an issue with our snippets?
