### ISSUE TITLE
Dont mUse Hungarian notation in kotlin snippets

### ISSUE THREAD

**Issue by the-dagger** [firebase/snippets-android#52]
In reference to what @supercilex mentioned here, we should avoid hungarian notation in our Kotlin snippets.

https://twitter.com/SUPERCILEX/status/1050544888733818880?s=19

**Comment by SUPERCILEX** [comment]
The best thing would be to follow the official style guide: https://android.github.io/kotlin-guides/style.html.

And here are the naming conventions: https://android.github.io/kotlin-guides/style.html#naming-1

**Comment by samtstern** [comment]
Yep sounds good.  I'm gonna do this on quickstart-android as well.  Ideally
we'd get ktlint or some other tool into the build too.

**Comment by the-dagger** [comment]
Yeah, makes sense.
I'll add it here and you can proceed with the quickstart. 👍
