### ISSUE TITLE
Phone Authentication Firebase

### ISSUE THREAD

**Issue by dhruvkaushal11** [firebase/snippets-android#77]
From 22nd January Android Play Services is unable to detect the Auto-Complete for the OTP.
Is there any guide which needs to be followed like SMS API in case of Firebase Phone Auth?

**Comment by samtstern** [comment]
@dhruvkaushal11 this doesn't seem to have anything to do with the snippets-android repo and there's not enough information to debug.  If you're having a problem with the Firebase Auth SDK please file an issue on the firebase-android-sdk repo with code, logs, and other details.
